---
# Update with apt / apt-get


- name: Adding keys
  apt_key:
    id: "{{ item }}"    
    keyserver: hkp://keyserver.ubuntu.com
    state: present
  loop:  
    - 379CE192D401AB61
    - C6ABDCF64DB9A0B2

- name: Remove php stretch repo
  apt_repository: 
    repo: 'deb https://packages.sury.org/php/ stretch main' 
    state: absent

- name: Add php buster repo
  apt_repository: 
    repo: 'deb https://packages.sury.org/php/ buster main' 
    state: present
    
- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 600
