---
# My Raspberry Pi and other Debian hosts

all:
    children:
        pi:
            children:
                cluster:
                    # Cluster of 4 Pi
                    hosts:
                        cpi[0:3]:
                nocluster:
                    hosts:
                        ltegateway:
                        pi[1:2]:
                        e[1:2]:    # Pi im Gemeindezentrum
        vserver:
            hosts:
                byggvir:     # Not a Pi but ...
        samba:
            hosts:
                pi[1:2]:
...
