---
# My Raspberry Pi and other Debian hosts
all:
    children:
        pi:
            children:
                cluster:
                    # Cluster of 4 Pi
                    hosts:
                        cpi[0:3].arend.tksd:
                other:
                    hosts:
                        pi1.dyn.byggvir.de:     # Pi Server 1
                        pi-e.dyn.byggvir.de:    # Pi im Gemeindezentrum
                        pisvr.arend.tksd:       # Pi Server 2 with 2 TB
            vars:
                ansible_user: pi
        vserver:
            hosts:
                byggvir.de: # Not a Pi but ...
            vars:
                ansible_user: thomas
        pc:
            hosts:
                dt-thomas.arend.tksd:   # My desktop
                lt-thomas.arend.tksd:   # My laptop
            vars:
                ansible_user: thomas
        gateways:
            hosts:
                pi1.dyn.byggvir.de:
                pi-e.dyn.byggvir.de:
                cpi[0:3].arend.tksd:
