---
# My Raspberry Pis

all:
    children:
        pi:
            children:
                cluster:
                    # Cluster of 4 Pi
                    hosts:
                        cpi[0:3]:
                nocluster:
                    hosts:
                        gateway:
                        pi[1:2]:
                        e[1:2]:    # Pi im Gemeindezentrum
        samba:
            hosts:
                pi[1:2]:
...
