# supernode/tasks/main.yaml

# Configure LAN Interfaces in /etc/network/interfaces.conf

# Create temprary directory for testing Ansible

- name: Create /etc/network
  file:
    path: /etc/network
    state: directory
    mode: 0755

# Create directory for interfaces

- name: Create /etc/network/interfaces.d
  file:
    path: /etc/network/interfaces.d
    state: directory
    mode: 0755

- name: Enable IPv4 forwarding
  lineinfile: 
    path: /etc/sysctl.conf
    line: 'net.ipv4.ip_forward=1'

- name: Enable IPv6 forwarding
  lineinfile: 
    path: /etc/sysctl.conf
    line: 'net.ipv6.conf.all.forwarding=1'

# Configure default Interfaces

#- name: Supernode LAN 
#  template:
#    src: iface-lan.j2
#    dest: /etc/network/interfaces
#    owner: root
#    group: root
#    mode: 0644

# Configure GRE Tunnles in /etc/network/interfaces.d/{{ item }}.conf

- name: FFRL GRE Tunnel configuration
  template:
    src: iface-gre-tunnel.j2
    dest: "/etc/network/interfaces.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ gre | list }}"
#  when: "{{ gre is defined }}"

- name: Restart networking
  service:
    name: networking
    state: restarted
