---
# Upatde with apt / apt-get

- name: apt install initial packages
  become: yes
  apt:
    name: 
        - findutils
        - fortune
        - pwgen
        - sudo
        - vim
    update_cache: yes
- name: apt install apache2 and php7
  become: yes
  apt:
    name: 
        - apache2-utils
        - libapache2-mod-php7.0
        - libapache2-mod-proxy-uwsgi
        - php7.0
        - php7.0-mysql
        - php-xml
        - php-mbstring
        - php-intl
        - php-cli
        - imagemagick
    update_cache: no
- name: apt install dns mysql and mail
  become: yes
  apt:
    name: 
        - unbound
        - dnsutils
        - resolvconf
        - certbot
        - mariadb-server
        - dovecot-core
        - dovecot-pop3d
        - dovecot-antispam
        - dovecot-managesieved
        - dovecot-sieve
        - dovecot-mysql
        - dovecot-imapd
        - dovecot-lmtpd
        - postfix
        - postfix-mysql
        - redis-server
        - cyrus-sasl2-doc
        - libsasl2-modules
    update_cache: no
