---
# Erstellt von: Thomas Arend
# Erstellt am:  2019-06-23

- name: "Install packages for NTP"
  apt:
    name: 
        - ntp
        - ntpstat        
    update_cache: yes
    state: present
    
- name: Delete servers and pool from ntp.conf
  lineinfile:
    dest: /etc/ntp.conf
    regexp: '(^pool|^server) .*'
    state: absent
  when: ntpprovider is defined
  notify:
    - restart ntp

- name: Insert server into /etc/ntp.conf
  lineinfile:
    path: /etc/ntp.conf
    line: "server {{ item }} iburst"
  loop: "{{ ntp_server[ntpprovider] | list }}"
  when: ntpprovider is defined
  notify:
    - restart ntp
    
- meta: flush_handlers
...
