---
# Erstellt von: Thomas Arend
# Erstellt am:  2019-06-23
# Geändert am:  2021-04-21

ntp_server:
  hetzner:
    - "213.239.239.164"
    - "213.239.239.165"
  #hetzner:
    #- "ntp1.hetzner.de"
    #- "ntp2.hetzner.com"
    #- "ntp3.hetzner.net"
    #- "213.239.239.166"

  home:
    - "192.168.20.1"
  kirche:
    - "192.168.30.1"
  juze:
    - "192.168.40.1"
  strato:
    - "ntp1.rz-ip.net"
    - "ntp2.rz-ip.net"
    - "ntps1-0.eecsit.tu-berlin.de" 
    - "ntps1-1.eecsit.tu-berlin.de"
    - "time.fu-berlin.de" 
  tonline:
    - "ntp1.t-online.de"
  fritzbox:
    - "192.168.178.1"
  speedport:
    - "192.168.2.1"
  azure:
    - "time.windows.com"
  ewetel:
    - "ntp0.ewetel.de"
    - "ntp1.ewetel.de"
  freenet:
    - "ntp0.freenet.de"
    - "ntp1.freenet.de"
  web.de:
    - "ntp.web.de"
  arco:
    - "de.pool.ntp.arcor-ip.net"
  versatel:
    - "time.versatel.de"
    - "ntp1.versatel.net"
    - "ntp2.versatel.net"
...
