---
# Upatde with apt / apt-get

    
- name: apt install apache2 and php 8.0
  become: yes
  apt:
    name: 
        - apache2
        - apache2-utils
        - libapache2-mod-php{{ item }}
        - libapache2-mod-proxy-uwsgi
        - imagemagick
    state: present
    update_cache: yes
  loop:
    - 8.0
    
#- name: Enable apache modules
  #become: yes
  #become_method: sudo
  #apache2_module:
    #state: present
    #name:
        #- socache_dbm
        #- socache_memcache
        #- ssl

#- name: Disable apache modules
  #become: yes
  #become_method: sudo
  #apache2_module:
    #state: absent
    #name:
        #- gnutls        

- name: enable apache2 modules
  raw: sudo a2enmod ssl socache*

#- name: disable apache2 modules
  #raw: sudo a2dismod gnutls
  
- name: apt install dns
  become: yes
  become_method: sudo
  apt:
    name: 
        - bind9
        - dnsutils
        - resolvconf
        - certbot
    update_cache: yes

...
