---
ansible_host: cpi1.arend.tksd
ansible_user: pi

gre:
  bb-a:
    tunnel:
        remote: 192.168.2.42
        local:  '{{ ansible_default_ipv4.address }}'
        netmask: 255.255.255.254
        mtu: 1400
        ttl: 64
    dev: tun-bb-a
    address: 100.64.200.9
    daddress: 100.64.200.10
    network: 100.64.0.200.8/30
  bb-b:
    tunnel:
        remote: 192.168.2.43
        local:  '{{ ansible_default_ipv4.address }}'
        netmask: 255.255.255.254
        mtu: 1400
        ttl: 64
    dev: tun-bb-b
    address: 100.64.200.11
    daddress: 100.64.200.13
    network: 100.64.200.12/30
...
