---
ansible_host: cpi2.arend.tksd
ansible_user: pi

gre:
  bb-a:
    tunnel:
        remote: 192.168.2.40
        local:  '{{ ansible_default_ipv4.address }}'
        netmask: 255.255.255.254
        mtu: 1400
        ttl: 64
    dev: tun-bb-a
    address: 100.64.200.2
    daddress: 100.64.200.1
    network: 100.64.0.200.0/30
  bb-b:
    tunnel:
        remote: 192.168.2.41
        local:  '{{ ansible_default_ipv4.address }}'
        netmask: 255.255.255.254
        mtu: 1400
        ttl: 64
    dev: tun-bb-b
    address: 100.64.200.10
    daddress: 100.64.200.9
    network: 100.64.200.8/30
...
