---

- name: Install minimal system requirements for ansible
  hosts: all
  gather_facts: false
  become: yes
  become_method: sudo
  tasks:
    - include_role:
        name: ansible-compatible
  tags:
    - minimumreq
...
