---
- name: Install common components
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - include_role:
        name: common

- name: Install samba
  hosts: samba
  gather_facts: false
  become: true
  tasks:
    - include_role:
        name: samba


...
