---
# Playbook to tes a single role

- name: Install common components
  hosts: all
  gather_facts: true
  become: yes
  tasks:
    - include_role:
        name: "{{ inc_role }}"
      loop:
        - ip-forward
      #  - reboot
        
      loop_control: 
        loop_var: inc_role
...
