# supernode/tasks/main.yaml

# Configure LAN Interfaces in /etc/network/interfaces.conf

# Create temprary directory for testing Ansible

- name: Create /etc/network
  file:
    path: /etc/network
    state: directory
    mode: 0755

# Create directory for interfaces

- name: Create /etc/network/interfaces.d
  file:
    path: /etc/network/interfaces.d
    state: directory
    mode: 0755

- name: Set net.ipv4.ip_forward
  sysctl:
    name: "net.ipv4.ip_forward"
    value: "1"
    sysctl_set: yes
    state: present
    reload: no

- name: Set net.ipv6.conf.all.forwarding
  sysctl:
    name: "net.ipv6.conf.all.forwarding"
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

# Configure GRE Tunnles in /etc/network/interfaces.d/{{ item }}.conf

- name: FFRL GRE Tunnel configuration
  template:
    src: iface-gre-tunnel.j2
    dest: "/etc/network/interfaces.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ gre | list }}"
  when: gre is defined

- name: Restart networking
  service:
    name: networking
    state: restarted
